### PR TITLE
Fix batch optional earnest

### PR DESCRIPTION
**Pull request by amarrella**
This is the generated code that maps to https://github.com/brendanhay/amazonka/pull/561

### CODE REVIEW

**Comment by quasi-coherent** [comment]
We haven't been strictly adhering to this, but I think the strategy is to merge just config changes to the develop branch, merge those into develop-gen, and then running the code gen there, right @andreyk0 ?

**Comment by quasi-coherent** [comment]
Oh, not fast enough I guess...

**Comment by amarrella** [comment]
oh, sorry @quasi-coherent ! I'll revert

**Comment by fiadliel** [comment]
The histories of those branches have definitely diverged, so either we have to reset the `develop-gen` branch, or cherry-pick changes.

**Comment by quasi-coherent** [comment]
Yeah, it's a bit of a mess (and I've played a part in that).  I think @andreyk0 had an idea for how it should work, but it might be too onerous to do that if you need the changes, Alessandro.

**Comment by quasi-coherent** [comment]
It's harder to submit PRs upstream this way, because Brenden has it set up that way too (i.e., only submit PRs that change configs).

**Comment by amarrella** [comment]
it is not urgent for me actually, i have a workaround for the issue (catch the parser error and move on...). Let me know what you think is the best way and I'll do it :) 

Upstream i already submitted a "clean" PR from a separate branch. https://github.com/brendanhay/amazonka/pull/561

**Comment by andreyk0** [comment]
Yeah, my original idea was to also (following upstream) separate config/gen stuff and since we don't own the project only apply autogen changes to our own separate branch  (which requires config merges to it).  That said, if anyone has a better idea - I'm all :ear: :ear: 

We need to either find time somehow to clean this thing up or figure out what to do about our reliance on it.

**Pull request merged**
